[general]
password = "AVNS_ERXe8j5gIX5yis97hnw"
user = "avnadmin"
database = "defaultdb"
ADMIN_USERNAME = "admins"
ADMIN_PASSWORD = "jon6y.crae"
GROQ_API_KEY = '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'
